[general]
password = "AVNS_ERXe8j5gIX5yis97hnw"
user = "avnadmin"
database = "defaultdb"
ADMIN_USERNAME = "admins"
ADMIN_PASSWORD = "jon6y.crae"
GROQ_API_KEY = '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'
